#!/usr/bin/env bash

# Will install the following list of packages
# using Homebrew package manager:

PACKAGES="
zsh
bash
git
git-extras
ripgrep
bat
tree
eth-p/software/bat-extras
exa
cloc
jq
"
#midnight-commander

brew update
xargs brew install <<< "$PACKAGES"

