#!/usr/bin/env bash

set -euo pipefail

#
# Copy the file into current directory and stash them
#

fileToInstall=".gitattributes"


cp $(dirname "$0")/"$fileToInstall" "${PWD}/${fileToInstall}"  # install

# Stash if in an initialized Git repo
[[ $(git rev-parse --is-inside-work-tree 2>/dev/null) ]] &&
  git add "${fileToInstall}"

